### ISSUE TITLE
tag.sh sammenligner med feil branch

### ISSUE THREAD

**Issue by Szune** [navikt/familie-klage#250]
Usikker på hvis dere i det hele tatt bruker `tag.sh`, men [den sammenligner med "master" i stedet for "main"](https://github.com/navikt/familie-klage/blob/main/.github/tag.sh#L5).

Ha en god uke :)

**Comment by eirarset** [comment]
Takk for heads up :) Vi bruker ikke scriptet, men det har nok bare hengt med fra en kopi av et tidligere prosjektet. Gjort klar en PR for å fikse det.
